#!/bin/bash

label=$(echo $JOB_NAME | perl -ne '/label=(.*)$/ && print "$1";')
sub="${0}-${label}"

if [ ! -x "$sub" ]; then
    echo "ERROR: missing sub-build script: $sub"
    exit 1
fi

$sub $*
exit $?
